[package]
name = "canpack-macros"
version = "0.0.1"
description = "Canpack Rust procedural macros"
authors = ["Ryan Vandersmith"]
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
