[package]
name = "canpack-macros"
version = "0.0.2"
description = "Canpack Rust procedural macros"
authors = ["Ryan Vandersmith"]
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
