// Generated by Canpack

#![allow(unused_imports)]

use candid::candid_method;
use ic_cdk::{query, update};

// __parts__

#[cfg(any(target_arch = "wasm32", test))]
fn main() {}

#[cfg(not(any(target_arch = "wasm32", test)))]
fn main() {
    candid::export_service!();
    println!("{}", __export_service());
}
