[package]
name = "canpack-example-hello"
version = "0.1.0"
description = "An example Rust crate with Canpack compatibility"
authors = ["Ryan Vandersmith"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
canpack = { version = "0.0.1", path = "../canpack" }
