[package]
name = "canpack"
version = "0.0.1"
description = "Canpack Rust utilities"
authors = ["Ryan Vandersmith"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
canpack-macros = { version = "0.0.1", path = "../canpack-macros" }
